
Reverse accessors for foreign keys clashing



-> From the shell to verify that we added a User model...
from django.contrib.auth.models import User
User.objects.count()

Adding the following path..
path('accounts/', include('django.contrib.auth.urls')),

Will give us access to the following URLs

accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']

<link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">